name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use-case or pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed API / solution
      description: |
        How should this look in code?
      render: typescript

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
