import type { ExchangeId, ExchangeInfo } from "./types.js";

export const EXCHANGES: Record<ExchangeId, ExchangeInfo> = {
  NYSE: {
    id: "NYSE",
    name: "New York Stock Exchange",
    mic: "XNYS",
    timezone: "America/New_York",
    openTime: "09:30",
    closeTime: "16:00",
    preOpenTime: "04:00",
    postCloseTime: "20:00",
    currency: "USD",
  },
  NASDAQ: {
    id: "NASDAQ",
    name: "Nasdaq Global Select Market",
    mic: "XNAS",
    timezone: "America/New_York",
    openTime: "09:30",
    closeTime: "16:00",
    preOpenTime: "04:00",
    postCloseTime: "20:00",
    currency: "USD",
  },
  LSE: {
    id: "LSE",
    name: "London Stock Exchange",
    mic: "XLON",
    timezone: "Europe/London",
    openTime: "08:00",
    closeTime: "16:30",
    preOpenTime: "07:50",
    postCloseTime: "17:15",
    currency: "GBP",
  },
  TSX: {
    id: "TSX",
    name: "Toronto Stock Exchange",
    mic: "XTSE",
    timezone: "America/Toronto",
    openTime: "09:30",
    closeTime: "16:00",
    preOpenTime: "07:00",
    postCloseTime: "17:00",
    currency: "CAD",
  },
  ASX: {
    id: "ASX",
    name: "Australian Securities Exchange",
    mic: "XASX",
    timezone: "Australia/Sydney",
    openTime: "10:00",
    closeTime: "16:00",
    preOpenTime: "07:00",
    postCloseTime: "16:12",
    currency: "AUD",
  },
  XETRA: {
    id: "XETRA",
    name: "Xetra (Frankfurt Stock Exchange)",
    mic: "XETR",
    timezone: "Europe/Berlin",
    openTime: "09:00",
    closeTime: "17:30",
    preOpenTime: "08:00",
    postCloseTime: "20:00",
    currency: "EUR",
  },
  NSE: {
    id: "NSE",
    name: "National Stock Exchange of India",
    mic: "XNSE",
    timezone: "Asia/Kolkata",
    openTime: "09:15",
    closeTime: "15:30",
    preOpenTime: "09:00",
    postCloseTime: "16:00",
    currency: "INR",
  },
  BSE: {
    id: "BSE",
    name: "BSE (Bombay Stock Exchange)",
    mic: "XBOM",
    timezone: "Asia/Kolkata",
    openTime: "09:15",
    closeTime: "15:30",
    preOpenTime: "09:00",
    postCloseTime: "16:00",
    currency: "INR",
  },
  CRYPTO: {
    id: "CRYPTO",
    name: "Crypto Market",
    mic: "",
    timezone: "UTC",
    openTime: "00:00",
    closeTime: "23:59",
    preOpenTime: "00:00",
    postCloseTime: "23:59",
    currency: "USD",
    alwaysOpen: true,
  },
};
